version: "3.0"
services:
  humble:
    image: stvl_build:humble
    build: .
    user: user
    stdin_open: True
    tty: True
    volumes:
      - .:/home/user/ros_ws/:rw
  iron:
    image: stvl_build:iron
    build: .
    user: user
    stdin_open: True
    tty: True
    volumes:
      - .:/home/user/ros_ws/:rw
