version: "3.0"
services:
  stvl:
    image: stvl_build:latest
    build: .
    user: user
    stdin_open: True
    tty: True
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - .:/home/user/ros_ws/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/home/user/.Xauthority
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
