name: ROS 2 STVL Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ros2_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [humble, iron]
    container: osrf/ros:${{ matrix.release }}-desktop
    steps:
      - uses: actions/checkout@v3
      - name: Run colcon
        run: source /opt/ros/${{ matrix.release }}/setup.bash && colcon build --event-handlers console_direct+
        shell: bash
